services:
  - type: web
    name: yasmin-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: yasmin_chat
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
