services:
  - type: web
    name: yasmine-chat-app
    env: python
    plan: free # أو خطة مدفوعة
    region: frankfurt # اختر المنطقة المناسبة
    buildCommand: "pip install -r requirements.txt && python main.py db_create_all"
    startCommand: "gunicorn app:app --workers 4 --threads 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: yasmine-db # يجب أن يتطابق مع اسم قاعدة البيانات في Render
          property: connectionString
      - key: HUGGINGFACE_API_TOKEN
        sync: false # أدخله كـ Secret في Render
      - key: GOOGLE_API_KEY # اختياري
        sync: false # أدخله كـ Secret في Render
      - key: FLASK_ENV
        value: production
      # - key: SESSION_SECRET
      #   generateValue: true

databases:
  - name: yasmine-db
    databaseName: yasmine_db
    user: yasmine_user
    plan: free
    region: frankfurt
