services:
  - type: web
    name: yasmin-gpt
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: sqlite+pysqlite:///local.db
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
